### ISSUE TITLE
[Week019] table clarification?

### ISSUE THREAD

**Issue by flukejones** [amroibrahim/DIYDoom#40]
### Patch Column Data
| Field Size | Data Type | Content                                |  
|------------|-----------|----------------------------------------|  
| 0x00-0x01  |    byte   | Offset (Y Offset) terminated with 0xFF |
| 0x02-0x03  |    byte   | Length of data                         |
| 0x04-0x05  |    byte   | Padding byte (not used)                |
| 0x06-0x??  |   Length  | (Data) pixels; an index into  palette  |
| 0x00-0x01  |    byte   | Padding byte (not used)                |

I think the 4th row could use further description? "Pixel Data, each byte is an index into palette".

**Comment by amroibrahim** [comment]
Agree, can you create a pull request?

**Comment by amroibrahim** [comment]
fixed thanks for reporting
