### ISSUE TITLE
[Week007] left/right vs front/back

### ISSUE THREAD

**Issue by flukejones** [amroibrahim/DIYDoom#43]
(Week007)
>"A splitter is chosen, and then everything is on the front or the back of that splitter (sometimes they >also call it left and right, I decided not to go with this convention due to the fact that the left is not >always the left and right is not always right. Left could be on the right and right could be on the left. If >you got confused, you’re on the right track. Using left and right will get confusing so front and back is >better so no assumptions in direction would be done).
>
>The front and back are based on the direction of the first vertex moving to the second vertex >(mathematically called vector, the direction you go moving to the second point)."

I wonder if we can clarify this better. Going against convention can make things confusing for others.

The way I understand the Linedefs and left/right is this: each linedef has a start and an end point, the start point means the line travels *from* this point, to the end point which is where it finishes. This gives the line a *direction*. Now, because the line has a direction we know which side is left and which side is right. Sectors are *always* on the right if the line is not double-sided (eg, not a portal).

You can interchange front==right and left==back, but we need to communicate how each convention is arrived at.

**Comment by amroibrahim** [comment]
Yes, you are right, I will add few diagrams to be more describe.

**Comment by amroibrahim** [comment]
I have updated all projects and articles, I home I haven’t missed any.
