### ISSUE TITLE
Discord Link not working

### ISSUE THREAD

**Issue by Eschryn** [amroibrahim/DIYDoom#45]
The link to your discord server is invalid
https://github.com/amroibrahim/DIYDoom/blame/master/DIYDOOM/Week020/notes/README.md#L380

**Comment by amroibrahim** [comment]
Thank you for letting me know! 
I have updated the link, please let me know if that fixes the issue so I can close it

**Comment by Eschryn** [comment]
You didn't change it to an invite - it's a channel link - it only works for those who already joined.

**Comment by amroibrahim** [comment]
Done, hopefully it is fixed now, turns out it is possible to set an expiration date for an invite link. 
Thanks, will add your user name to the Thank you list (let me know if you want me to add you under a different name).
