### ISSUE TITLE
how exactly can you run and/or build the project?

### ISSUE THREAD

**Issue by Vantablack3301** [amroibrahim/DIYDoom#47]
I have everything downloaded and i first tried running it in vscode but that didn't seem to work so I tried opening it up in visual studio 2019 and it gave me 400 errors and didn't run. I'm still new to visual studio and I'm not totally sure how to work with it properly. am i doing something wrong?

**Comment by vibrantrida** [comment]
You are supposed to follow along, If you don't you won't be able to build the most recent "week".

**Comment by amroibrahim** [comment]
Can you paste the exact error and which week you seeing the error? All weeks should compile.
